/** @type {import('next').NextConfig} */
import path from 'node:path';

const nextConfig = {
  output: 'export',
  outputFileTracingRoot: process.cwd(),
  basePath: '',
  trailingSlash: true,
  compress: true,
  poweredByHeader: false,
  productionBrowserSourceMaps: false,
  images: {
    unoptimized: true,
    remotePatterns: [{ protocol: 'https', hostname: '**' }],
  },
  typescript: {
    ignoreBuildErrors: true,
  },
  webpack: (config) => {
    const appDir = path.join(process.cwd(), 'app');
    config.resolve.alias = {
      ...(config.resolve.alias || {}),
      '@': appDir,
      'ncomponents': path.join(appDir, 'components'),
      'ndata': path.join(appDir, 'data'),
      'nlib': path.join(appDir, 'lib'),
    };
    return config;
  },
  generateBuildId: async () => 'zion-tech-group-v1',
  async redirects() {
    return [
      { source: '/agents/monitoring', destination: '/agents-monitoring', permanent: true },
      { source: '/agents/monitoring/:splat*', destination: '/agents-monitoring/:splat*', permanent: true },
      { source: '/services/ai-services', destination: '/services/?category=ai', permanent: true },
      { source: '/services/cloud-services', destination: '/services/?category=cloud', permanent: true },
      { source: '/services/cybersecurity', destination: '/services/?category=security', permanent: true },
      { source: '/services/data-analytics', destination: '/services/?category=data', permanent: true },
      { source: '/services/devops-services', destination: '/services/?category=devops', permanent: true },
      { source: '/services/iot-platform', destination: '/services/?category=iot', permanent: true },
      { source: '/services/it-services', destination: '/services/?category=it', permanent: true },
      { source: '/services/security-services', destination: '/services/?category=security', permanent: true },
      { source: '/services/data-services', destination: '/services/?category=data', permanent: true },
      { source: '/services/micro-saas-services', destination: '/services/?category=micro-saas', permanent: true },
      { source: '/ai-services/', destination: '/services/?category=ai', permanent: true },
      { source: '/cloud-services/', destination: '/services/?category=cloud', permanent: true },
      { source: '/cybersecurity/', destination: '/services/?category=security', permanent: true },
      { source: '/data-analytics/', destination: '/services/?category=data', permanent: true },
      { source: '/devops-services/', destination: '/services/?category=devops', permanent: true },
      { source: '/iot-platform/', destination: '/services/?category=iot', permanent: true },
      { source: '/it-services/', destination: '/services/?category=it', permanent: true },
      { source: '/security-services/', destination: '/services/?category=security', permanent: true },
      { source: '/micro-saas-services/', destination: '/services/?category=micro-saas', permanent: true },
      { source: '/help', destination: '/faq', permanent: true },
      { source: '/ai-agents', destination: '/services/ai-agents-autonomous', permanent: true },
      { source: '/ai-agents/', destination: '/services/ai-agents-autonomous/', permanent: true },
      { source: '/ai-chat-companion', destination: '/ai-services', permanent: true },
      { source: '/ai-chat-companion/', destination: '/ai-services/', permanent: true },
      { source: '/ai-financial-services', destination: '/ai-fraud-detection', permanent: true },
      { source: '/ai-financial-services/', destination: '/ai-fraud-detection/', permanent: true },
      { source: '/services/ai-chatbot-builder-pro', destination: '/services/ai-chatbot-builder', permanent: true },
      { source: '/services/ai-chatbot-builder-pro/', destination: '/services/ai-chatbot-builder/', permanent: true },
      { source: '/services/ai-fraud-detection', destination: '/ai-fraud-detection', permanent: true },
      { source: '/services/ai-fraud-detection/', destination: '/ai-fraud-detection/', permanent: true },
      { source: '/services/ai-automation', destination: '/services/?category=ai', permanent: true },
      { source: '/services/ai-automation/', destination: '/services/?category=ai', permanent: true },
      { source: '/services/it-outsourcing', destination: '/services/?category=it', permanent: true },
      { source: '/services/it-outsourcing/', destination: '/services/?category=it', permanent: true },
      { source: '/services/ai-network-performance-and-wan-optimization-for-it-in-2026', destination: '/services/ai-first-network-performance-and-wan-optimization-for-it-in-2026', permanent: true },
      { source: '/services/ai-network-performance-and-wan-optimization-for-it-in-2026/', destination: '/services/ai-first-network-performance-and-wan-optimization-for-it-in-2026/', permanent: true },
      { source: '/services/ai-endpoint-management-and-zero-trust-access-for-it-in-2026', destination: '/services/ai-first-endpoint-management-and-zero-trust-access-for-it-in-2026', permanent: true },
      { source: '/services/ai-endpoint-management-and-zero-trust-access-for-it-in-2026/', destination: '/services/ai-first-endpoint-management-and-zero-trust-access-for-it-in-2026/', permanent: true },
      { source: '/services/ai-development-acceleration', destination: '/services/', permanent: true },
      { source: '/services/ai-development-acceleration/', destination: '/services/', permanent: true },
      { source: '/services/ai-help-desk-automation', destination: '/services/', permanent: true },
      { source: '/services/ai-help-desk-automation/', destination: '/services/', permanent: true },
      { source: '/services/devops-automation-consulting', destination: '/services/', permanent: true },
      { source: '/services/devops-automation-consulting/', destination: '/services/', permanent: true },
      { source: '/services/fleet-management-gps-tracking', destination: '/services/', permanent: true },
      { source: '/services/fleet-management-gps-tracking/', destination: '/services/', permanent: true },
      { source: '/services/lead-generation-outreach-automation', destination: '/services/', permanent: true },
      { source: '/services/lead-generation-outreach-automation/', destination: '/services/', permanent: true },
      { source: '/services/ai-anti-money-laundering-intelligence', destination: '/services/', permanent: true },
      { source: '/services/ai-anti-money-laundering-intelligence/', destination: '/services/', permanent: true },
      { source: '/services/ai-kyc-identity-verification', destination: '/services/', permanent: true },
      { source: '/services/ai-kyc-identity-verification/', destination: '/services/', permanent: true },
      { source: '/services/ai-credit-risk-scoring', destination: '/services/', permanent: true },
      { source: '/services/ai-credit-risk-scoring/', destination: '/services/', permanent: true },
      { source: '/services/ai-telemedicine-platform', destination: '/services/', permanent: true },
      { source: '/services/ai-telemedicine-platform/', destination: '/services/', permanent: true },
      { source: '/services/ai-personalized-product-recommendations', destination: '/services/', permanent: true },
      { source: '/services/ai-personalized-product-recommendations/', destination: '/services/', permanent: true },
      { source: '/services/ai-route-optimizer-pro', destination: '/services/', permanent: true },
      { source: '/services/ai-route-optimizer-pro/', destination: '/services/', permanent: true },
      { source: '/services/5g-ai-code-generation--optimization-cb3ddf63', destination: '/services/', permanent: true },
      { source: '/services/5g-ai-code-generation--optimization-cb3ddf63/', destination: '/services/', permanent: true },
      { source: '/services/5g-ai-customer-churn-prediction-3f074c6f', destination: '/services/', permanent: true },
      { source: '/services/5g-ai-customer-churn-prediction-3f074c6f/', destination: '/services/', permanent: true },
      { source: '/services/5g-ai-financial-planning--analysis-41f76ffa', destination: '/services/', permanent: true },
      { source: '/services/5g-ai-financial-planning--analysis-41f76ffa/', destination: '/services/', permanent: true },
      { source: '/services/5g-ai-powered-disaster-recovery-0f33bdf8', destination: '/services/', permanent: true },
      { source: '/services/5g-ai-powered-disaster-recovery-0f33bdf8/', destination: '/services/', permanent: true },
      { source: '/services/5g-ai-powered-market-intelligence-5f01aacd', destination: '/services/', permanent: true },
      { source: '/services/5g-ai-powered-market-intelligence-5f01aacd/', destination: '/services/', permanent: true },
      { source: '/services/5g-ai-powered-predictive-analytics-suite-26ad0aab', destination: '/services/', permanent: true },
      { source: '/services/5g-ai-powered-predictive-analytics-suite-26ad0aab/', destination: '/services/', permanent: true },
      { source: '/services/5g-ai-powered-resource-management-48c54592', destination: '/services/', permanent: true },
      { source: '/services/5g-ai-powered-resource-management-48c54592/', destination: '/services/', permanent: true },
      { source: '/services/5g-ai-powered-seo-content-engine-10368583', destination: '/services/', permanent: true },
      { source: '/services/5g-ai-powered-seo-content-engine-10368583/', destination: '/services/', permanent: true },
      { source: '/blog/predictable-ai-roi-in-education', destination: '/blog/', permanent: true },
      { source: '/blog/predictable-ai-roi-in-education/', destination: '/blog/', permanent: true },
      { source: '/case-studies/healthcare-ai-diagnostics-platform-reduced-missed-conditions-by-41%', destination: '/case-studies/', permanent: true },
      { source: '/case-studies/healthcare-ai-diagnostics-platform-reduced-missed-conditions-by-41%25', destination: '/case-studies/', permanent: true },
      { source: '/pricing', destination: '/services/', permanent: false },
      { source: '/pricing/', destination: '/services/', permanent: false },
      { source: '/services/streaming-services', destination: '/services/', permanent: true },
      { source: '/services/streaming-services/', destination: '/services/', permanent: true },
      { source: '/services/ai-service-router', destination: '/services/', permanent: true },
      { source: '/services/ai-service-router/', destination: '/services/', permanent: true },
      { source: '/services/services-explorer', destination: '/services/', permanent: true },
      { source: '/services/services-explorer/', destination: '/services/', permanent: true },
      { source: '/services/testimonials', destination: '/case-studies/', permanent: true },
      { source: '/services/testimonials/', destination: '/case-studies/', permanent: true },
      { source: '/industries/manufacturing', destination: '/solutions/', permanent: false },
      { source: '/industries/manufacturing/', destination: '/solutions/', permanent: false },
    ];
  },
};

export default nextConfig;
