/** @type {import('next').NextConfig} */
const nextConfig = {
  async redirects() {
    return [
      { source: '/main', destination: '/', permanent: true },
      { source: '/front', destination: '/', permanent: true },
      { source: '/front/index', destination: '/', permanent: true },
      { source: '/.netlify/functions/auto-scheduler', destination: '/', permanent: true },
      { source: '/.netlify/functions/broken-image-scanner', destination: '/', permanent: true },
      { source: '/.netlify/functions/cloud_orchestrator', destination: '/', permanent: true },
      { source: '/.netlify/functions/continuous-front-runner', destination: '/', permanent: true },
      { source: '/.netlify/functions/continuous-orchestrator', destination: '/', permanent: true },
      { source: '/.netlify/functions/fast-front-promoter', destination: '/', permanent: true },
      { source: '/.netlify/functions/fast-orchestrator', destination: '/', permanent: true },
      { source: '/.netlify/functions/feature-advertiser', destination: '/', permanent: true },
      { source: '/.netlify/functions/features-capabilities-benefits-advertiser', destination: '/', permanent: true },
      { source: '/.netlify/functions/front-enhancer', destination: '/', permanent: true },
      { source: '/.netlify/functions/front-index-futurizer', destination: '/', permanent: true },
      { source: '/.netlify/functions/front-index-orchestrator', destination: '/', permanent: true },
      { source: '/.netlify/functions/front-index-scheduler', destination: '/', permanent: true },
      { source: '/.netlify/functions/front-maximizer', destination: '/', permanent: true },
      { source: '/.netlify/functions/frontpage-enhancer', destination: '/', permanent: true },
      { source: '/.netlify/functions/homepage_advertiser', destination: '/', permanent: true },
      { source: '/.netlify/functions/hyper-front-index-accelerator', destination: '/', permanent: true },
      { source: '/.netlify/functions/innovation-lab', destination: '/', permanent: true },
      { source: '/.netlify/functions/link-and-health-scheduler', destination: '/', permanent: true },
      { source: '/.netlify/functions/marketing-and-features-promo', destination: '/', permanent: true },
      { source: '/.netlify/functions/readme-advertiser', destination: '/', permanent: true },
      { source: '/.netlify/functions/schedule-content-index', destination: '/', permanent: true },
      { source: '/.netlify/functions/schedule-homepage', destination: '/', permanent: true },
      { source: '/.netlify/functions/schedule-knowledge-graph', destination: '/', permanent: true },
      { source: '/.netlify/functions/schedule-site-health', destination: '/', permanent: true },
      { source: '/.netlify/functions/sitemap_runner', destination: '/', permanent: true },
      { source: '/2025/08/03/the-uproar-over-vogues-ai-generated-ad-isnt-just-about-fashion/', destination: '/', permanent: true },
      { source: '/2025/08/04/spotify-raises-subscription-prices/', destination: '/', permanent: true },
      { source: '/2025/08/05/three-weeks-after-acquiring-windsurf-cognition-offers-staff-the-exit-door/', destination: '/', permanent: true },
      { source: '/2025/08/06/google-says-hackers-stole-its-customers-data-in-a-breach-of-its-salesforce-database/', destination: '/', permanent: true },
      { source: '/2025/08/06/instagram-takes-on-snapchat-with-new-instagram-map/', destination: '/', permanent: true },
      { source: '/2025/08/06/key-sections-of-the-us-constitution-deleted-from-governments-website/', destination: '/', permanent: true },
      { source: '/2025/08/07/tesla-shuts-down-dojo-the-ai-training-supercomputer-that-musk-said-would-be-key-to-full-self-driving/', destination: '/', permanent: true },
      { source: '/2025/08/08/dont-let-your-competitor-steal-the-brand-spotlight-secure-your-exhibit-table-at-techcrunch-disrupt-2025/', destination: '/', permanent: true },
      { source: '/2025/08/08/former-googlers-ai-startup-openart-now-creates-brainrot-videos-in-just-one-click/', destination: '/', permanent: true },
      { source: '/2025/08/08/how-to-use-instagram-map-and-protect-your-privacy/', destination: '/', permanent: true },
      { source: '/2025/08/08/impersonators-are-targeting-companies-with-fake-techcrunch-outreach/', destination: '/', permanent: true },
      { source: '/2025/08/08/meta-acquires-ai-audio-startup-waveforms/', destination: '/', permanent: true },
      { source: '/2025/08/08/nasa-and-google-are-building-an-ai-medical-assistant-to-keep-mars-bound-astronauts-healthy/', destination: '/', permanent: true },
      { source: '/2025/08/08/openai-priced-gpt-5-so-low-it-may-spark-a-price-war/', destination: '/', permanent: true },
      { source: '/2025/08/08/pinterest-ceo-says-agentic-shopping-is-still-a-long-way-out/', destination: '/', permanent: true },
      { source: '/2025/08/08/rip-microsoft-lens-a-simple-little-app-thats-getting-replaced-by-ai/', destination: '/', permanent: true },
      { source: '/2025/08/08/sam-altman-addresses-bumpy-gpt-5-rollout-bringing-4o-back-and-the-chart-crime/', destination: '/', permanent: true },
      { source: '/2025/08/08/softbank-reportedly-bought-foxconns-ohio-factory-for-the-stargate-ai-project/', destination: '/', permanent: true },
      { source: '/hands-on/756587/microsoft-copilot-3d-feature-hands-on', destination: '/', permanent: true },
      { source: '/motion/', destination: '/', permanent: true },
      { source: '/news/756444/openai-gpt-5-vibe-graphing-chart-crime', destination: '/', permanent: true },
      { source: '/storyline/google-i-o-2025-live-coverage-google-ai-ultra-project-mariner-gemini-app-updates-and-more/', destination: '/', permanent: true },
      { source: '/storyline/wwdc-2025-live-updates-a-fresh-look-for-ios-a-dedicated-gaming-app-and-more/', destination: '/', permanent: true },
      { source: '/Zion-Holdings/zion.app', destination: '/', permanent: true },
      { source: '/Zion-Holdings/zion.app/actions', destination: '/', permanent: true },
      { source: '/Zion-Holdings/zion.app/blob/main/docs/CHANGELOG_AI.md', destination: '/', permanent: true },
      { source: '/Zion-Holdings/zion.app/issues', destination: '/', permanent: true },
      { source: '/Zion-Holdings/zion.app/tree/main/automation', destination: '/', permanent: true },
      { source: '/Zion-Holdings/zion.app/tree/main/docs', destination: '/', permanent: true }
    ];
  },
};

module.exports = nextConfig;