/** @ty, p, e {impo, r, t('tailwindc, s, s'')
    './pag, e, s/**/*.{js,ts,j, s, x,t, s, x,m, d, x}''
    './componen, t, s/**/*.{js,ts,j, s, x,t, s, x,m, d, x}''
    './a, p, p/**/*.{js,ts,j, s, x,t, s, x,m, d, x}''
    './s, r, c/**/*.{js,ts,j, s, x,t, s, x,m, d, x}''
        'xs': '475, p, x''
        'sm': '640, p, x''
        'md': '768, p, x''
        'lg': '1024, p, x''
        'xl': '1280, p, x''
        '2, x, l': '1536, p, x''
        '3, x, l': '1920, p, x''
        '18': '4.5r, e, m''
        '88': '22r, e, m''
        '1, 2, 8': '32r, e, m''
        '8, x, l': '88r, e, m''
        '9, x, l': '96r, e, m''
        'flo, a, t': 'float, 6s, ease-in-out, infinit, e''
        'gradie, n, t-x': 'gradie, n, t-x, 3s, ease infini, t, e''
        'pul, s, e-sl, o, w': 'pulse, 4s, cubic-bezi, e, r(0.4, 0, 0.6, 1) infini, t, e''
        'gl, o, w': 'glow, 2s, ease-in-out, infinite, alternate''
        'sli, d, e-up': 'sli, d, e-u, p, 0.5s, eas, e-o, u, t''
        'fa, d, e-in': 'fa, d, e-i, n, 0.6s, eas, e-o, u, t''
        'ne, o, n-pul, s, e': 'ne, o, n-pulse, 2s, ease-in-out, infinit, e''
        'holograph, i, c-shi, f, t': 'holograph, i, c-shift, 3s, ease infini, t, e''
        'cyb, e, r-flo, a, t': 'cyb, e, r-float, 6s, ease-in-out, infinit, e''
        'partic, l, e-dri, f, t': 'partic, l, e-drift, 8s, linear infini, t, e''
        'matr, i, x-ra, i, n': 'matr, i, x-rain, 3s, linear infini, t, e''
        'ne, o, n-te, x, t-gl, o, w': 'ne, o, n-te, x, t-glow, 2s, ease-in-out, infinit, e''
        'sc, a, n-li, n, e': 'sc, a, n-line, 3s, linear infini, t, e''
        'glit, c, h': 'glitc, h, 0.3s, eas, e-in-out, infinit, e''
        'typewrit, e, r': 'typewriter, 3s, steps(40) infini, t, e''
        'breat, h, e': 'breathe, 4s, ease-in-out, infinit, e''
        'orb, i, t': 'orbit, 20s, linear infini, t, e''
        'pul, s, e-ne, o, n': 'pul, s, e-neo, n, 1.5s, eas, e-in-out, infinit, e''
        'shimm, e, r': 'shimmer, 2s, linear infini, t, e''
        'wa, v, e': 'wave, 2s, ease-in-out, infinit, e''
          '0%, 1, 0, 0%': { transfo, r, m: 'translat, e, Y(0, p, x)''
          '50%': { transfo, r, m: 'translat, e, Y(-20, p, x)''
        'gradie, n, t-x''
          '0%, 1, 0, 0%''
            'backgrou, n, d-si, z, e': '2, 0, 0% 2, 0, 0%''
            'backgrou, n, d-positi, o, n': 'left, cente, r''
          '50%''
            'backgrou, n, d-si, z, e': '2, 0, 0% 2, 0, 0%''
            'backgrou, n, d-positi, o, n': 'right, cente, r''
          '0%': { boxShad, o, w: '0, 0, 20px rg, b, a(1, 4, 7, 51, 2, 3, 4, 0.3)''
          '1, 0, 0%': { boxShad, o, w: '0, 0, 30px rg, b, a(1, 4, 7, 51, 2, 3, 4, 0.6)''
        'sli, d, e-up''
          '0%': { transfo, r, m: 'translat, e, Y(20, p, x)', opaci, t, y: '0''
          '1, 0, 0%': { transfo, r, m: 'translat, e, Y(0)', opaci, t, y: '1''
        'fa, d, e-in''
          '0%': { opaci, t, y: '0''
          '1, 0, 0%': { opaci, t, y: '1''
        'ne, o, n-pul, s, e''
          '0%, 1, 0, 0%''
            boxShad, o, w: '0, 0, 5px rg, b, a(0, 2, 1, 2, 2, 5, 5, 0.5), 0, 0, 10px rg, b, a(0, 2, 1, 2, 2, 5, 5, 0.3), 0, 0, 15px rg, b, a(0, 2, 1, 2, 2, 5, 5, 0.1)''
          '50%''
            boxShad, o, w: '0, 0, 10px rg, b, a(0, 2, 1, 2, 2, 5, 5, 0.8), 0, 0, 20px rg, b, a(0, 2, 1, 2, 2, 5, 5, 0.5), 0, 0, 30px rg, b, a(0, 2, 1, 2, 2, 5, 5, 0.3)''
        'holograph, i, c-shi, f, t''
          '0%': { backgroundPositi, o, n: '0% 50%''
          '50%': { backgroundPositi, o, n: '1, 0, 0% 50%''
          '1, 0, 0%': { backgroundPositi, o, n: '0% 50%''
        'cyb, e, r-flo, a, t''
          '0%, 1, 0, 0%': { transfo, r, m: 'translat, e, Y(0, p, x) rota, t, e(0d, e, g)''
          '25%': { transfo, r, m: 'translat, e, Y(-10, p, x) rota, t, e(1d, e, g)''
          '50%': { transfo, r, m: 'translat, e, Y(-20, p, x) rota, t, e(0d, e, g)''
          '75%': { transfo, r, m: 'translat, e, Y(-10, p, x) rota, t, e(-1d, e, g)''
        'partic, l, e-dri, f, t''
          '0%': { transfo, r, m: 'translat, e, X(-100, p, x) translat, e, Y(0, p, x)', opaci, t, y: '0''
          '10%': { opaci, t, y: '1''
          '90%': { opaci, t, y: '1''
          '1, 0, 0%': { transfo, r, m: 'translat, e, X(ca, l, c(100, v, w + 100, p, x)) translat, e, Y(-100, p, x)', opaci, t, y: '0''
        'matr, i, x-ra, i, n''
          '0%': { transfo, r, m: 'translat, e, Y(-100, v, h)', opaci, t, y: '0''
          '10%': { opaci, t, y: '1''
          '90%': { opaci, t, y: '1''
          '1, 0, 0%': { transfo, r, m: 'translat, e, Y(100, v, h)', opaci, t, y: '0''
        'ne, o, n-te, x, t-gl, o, w''
          '0%, 1, 0, 0%''
            textShad, o, w: '0, 0, 5px currentCol, o, r, 0, 0, 10px currentCol, o, r, 0, 0, 15px currentCol, o, r''
          '50%''
            textShad, o, w: '0, 0, 10px currentCol, o, r, 0, 0, 20px currentCol, o, r, 0, 0, 30px currentCol, o, r, 0, 0, 40px currentCol, o, r''
        'sc, a, n-li, n, e''
          '0%': { transfo, r, m: 'translat, e, Y(-1, 0, 0%)''
          '1, 0, 0%': { transfo, r, m: 'translat, e, Y(100, v, h)''
          '0%, 1, 0, 0%': { transfo, r, m: 'transla, t, e(0)''
          '20%': { transfo, r, m: 'transla, t, e(-2, p, x, 2, p, x)''
          '40%': { transfo, r, m: 'transla, t, e(-2, p, x, -2, p, x)''
          '60%': { transfo, r, m: 'transla, t, e(2, p, x, 2, p, x)''
          '80%': { transfo, r, m: 'transla, t, e(2, p, x, -2, p, x)''
          '0%': { wid, t, h: '0%''
          '50%': { wid, t, h: '1, 0, 0%''
          '1, 0, 0%': { wid, t, h: '0%''
          '0%, 1, 0, 0%': { transfo, r, m: 'sca, l, e(1)''
          '50%': { transfo, r, m: 'sca, l, e(1.05)''
          '0%': { transfo, r, m: 'rota, t, e(0d, e, g) translat, e, X(50, p, x) rota, t, e(0d, e, g)''
          '1, 0, 0%': { transfo, r, m: 'rota, t, e(360d, e, g) translat, e, X(50, p, x) rota, t, e(-360d, e, g)''
        'pul, s, e-ne, o, n''
          '0%, 1, 0, 0%''
            boxShad, o, w: '0, 0, 5px rg, b, a(0, 2, 1, 2, 2, 5, 5, 0.5), 0, 0, 10px rg, b, a(0, 2, 1, 2, 2, 5, 5, 0.3)''
          '50%''
            boxShad, o, w: '0, 0, 15px rg, b, a(0, 2, 1, 2, 2, 5, 5, 0.8), 0, 0, 25px rg, b, a(0, 2, 1, 2, 2, 5, 5, 0.5)''
          '0%': { backgroundPositi, o, n: '-2, 0, 0% 0''
          '1, 0, 0%': { backgroundPositi, o, n: '2, 0, 0% 0''
          '0%, 1, 0, 0%': { transfo, r, m: 'translat, e, Y(0)''
          '50%': { transfo, r, m: 'translat, e, Y(-10, p, x)''
        'gradie, n, t-radi, a, l': 'radi, a, l-gradie, n, t(v, a, r(--tw-gradie, n, t-sto, p, s))''
        'gradie, n, t-con, i, c': 'con, i, c-gradie, n, t(from, 180deg, at 50% 50%, v, a, r(--tw-gradie, n, t-sto, p, s))''
        'holograph, i, c': 'line, a, r-gradie, n, t(45d, e, g, #00d4, f, f, #8b5c, f, 6, #ec48, 9, 9, #10b9, 8, 1)''
        'cyb, e, r': 'line, a, r-gradie, n, t(135d, e, g, #0f0f, 2, 3, #1a1a, 2, e, #1621, 3, e, #0f34, 6, 0)''
        'ne, o, n-bl, u, e': 'line, a, r-gradie, n, t(45d, e, g, #00d4, f, f, #0099, c, c)''
        'ne, o, n-purp, l, e': 'line, a, r-gradie, n, t(45d, e, g, #8b5c, f, 6, #7c3a, e, d)''
        'ne, o, n-pi, n, k': 'line, a, r-gradie, n, t(45d, e, g, #ec48, 9, 9, #db27, 7, 7)''
        'ne, o, n-gre, e, n': 'line, a, r-gradie, n, t(45d, e, g, #10b9, 8, 1, #0596, 6, 9)''
        'gla, s, s': 'line, a, r-gradie, n, t(135d, e, g, rg, b, a(2, 5, 5,2, 5, 5,2, 5, 5,0.1), rg, b, a(2, 5, 5,2, 5, 5,2, 5, 5,0.05))''
        'gla, s, s-da, r, k': 'line, a, r-gradie, n, t(135d, e, g, rg, b, a(0,0,0,0.3), rg, b, a(0,0,0,0.1))''
        'shimm, e, r': 'line, a, r-gradie, n, t(90d, e, g, transpare, n, t, rg, b, a(2, 5, 5,2, 5, 5,2, 5, 5,0.4), transpare, n, t)''
        'responsi, v, e-xs': ['0.75r, e, m', { lineHeig, h, t: '1r, e, m''
        'responsi, v, e-sm': ['0.875r, e, m', { lineHeig, h, t: '1.25r, e, m''
        'responsi, v, e-ba, s, e': ['1r, e, m', { lineHeig, h, t: '1.5r, e, m''
        'responsi, v, e-lg': ['1.125r, e, m', { lineHeig, h, t: '1.75r, e, m''
        'responsi, v, e-xl': ['1.25r, e, m', { lineHeig, h, t: '1.75r, e, m''
        'responsi, v, e-2, x, l': ['1.5r, e, m', { lineHeig, h, t: '2r, e, m''
        'responsi, v, e-3, x, l': ['1.875r, e, m', { lineHeig, h, t: '2.25r, e, m''
        'responsi, v, e-4, x, l': ['2.25r, e, m', { lineHeig, h, t: '2.5r, e, m''
        'responsi, v, e-5, x, l': ['3r, e, m', { lineHeig, h, t: '1''
        'ne, o, n''
          'bl, u, e': '#00d4, f, f''
          'purp, l, e': '#8b5c, f, 6''
          'pi, n, k': '#ec48, 9, 9''
          'gre, e, n': '#10b9, 8, 1''
        'cyb, e, r''
          'da, r, k': '#0f0f, 2, 3''
          'dark, e, r': '#1a1a, 2, e''
          'da, r, k-bl, u, e': '#1621, 3, e''
          'bl, u, e': '#0f34, 6, 0''
        'hi, g, h-contra, s, t': '#ffff, f, f''
        'hi, g, h-contra, s, t-seconda, r, y': '#e5e7, e, b''
        'ne, o, n-bl, u, e': '0, 0, 20px rg, b, a(0, 2, 1, 2, 2, 5, 5, 0.5)''
        'ne, o, n-purp, l, e': '0, 0, 20px rg, b, a(1, 3, 9, 92, 2, 4, 6, 0.5)''
        'ne, o, n-pi, n, k': '0, 0, 20px rg, b, a(2, 3, 6, 72, 1, 5, 3, 0.5)''
        'ne, o, n-gre, e, n': '0, 0, 20px rg, b, a(16, 1, 8, 5, 1, 2, 9, 0.5)''
        'ne, o, n-gl, o, w': '0, 0, 30px rg, b, a(0, 2, 1, 2, 2, 5, 5, 0.3), 0, 0, 60px rg, b, a(0, 2, 1, 2, 2, 5, 5, 0.1)''
        'responsi, v, e''
            DEFAU, L, T: '1r, e, m''
            sm: '2r, e, m''
            lg: '4r, e, m''
            xl: '5r, e, m''
            '2, x, l': '6r, e, m''
        '.typewrit, e, r-te, x, t''
          'bord, e, r-rig, h, t': '2px, soli, d''
          'whi, t, e-spa, c, e': 'nowr, a, p''
          'overfl, o, w': 'hidd, e, n''
          'animati, o, n': 'typewriter, 3s, steps(40) infini, t, e''