<ForgotPassword />;
      <ResetPassword />;
      <UpdatePassword />;
      {/* Onboarding Routes */};
      <ProtectedRoute>;
        <Onboarding />;
      </ProtectedRoute>;
      <ProtectedRoute>;
        <TalentOnboarding />;
      </ProtectedRoute>;
      <ProtectedRoute>;
        <ServiceOnboarding />;
      </ProtectedRoute>;
    </>;