import React from "react";
import Sidebar from '../ui/Sidebar';';
import { useRouter } from 'next/router';
;
interface ModernLayoutProps {;
  children: React.ReactNode;
};
const ModernLayout: React.FC<ModernLayoutProps> = ({ children }) => {;
  const router = useRouter();";
;";";
  return (;";";";
    <div className="flex h-screen bg-gray-50">;";";";";";
      <Sidebar       />";";";";";";
      <main className="flex-1 overflow-auto">";";";";";";
        <div className="min-h-screen">;
          {children};
        </div>;
      </main>;";
    </div>;";";
  );";";";
};";";";";
;";";";";";
export default ModernLayout;";";";"';";";