import type { NextApiRequest, NextApiResponse } from 'next'
  type: 'service' | 'employment' | 'partnership' | 'nda' | 'license'
  if (req.method !== 'GET'
    return res.status(405).json({ error: 'Method not allowed'
      id: 'contract-1'
      name: 'Software Development Agreement'
      type: 'service'
      category: 'Technology'
      description: 'Standard agreement for software development services'
        'Scope of work'
        'Payment terms'
        'Intellectual property rights'
        'Confidentiality'
        'Termination'
      id: 'contract-2'
      name: 'Employment Contract'
      type: 'employment'
      category: 'Human Resources'
      description: 'Standard full-time employment contract template'
        'Job description'
        'Compensation & benefits'
        'Working hours'
        'Non-compete'
        'Termination'