import type { NextApiRequest, NextApiResponse } from 'next'
  if (req.method !== 'POST'
    return res.status(405).json({ error: 'Method not allowed'
    category: 'Web Development'
    complexity: 'high'
    estimatedDuration: '6-8 weeks'
    technologies: ['React', 'Node.js', 'MongoDB'
      'Responsive web application'
      'Admin dashboard'
      'API documentation'
      'Deployment guide'
    risks: ['Third-party integrations', 'Performance requirements'
    recommendations: ['Adopt Agile methodology', 'Schedule regular demos'