import { useLanguage } from '@/context/LanguageContext';
import { formatPriceByLocale } from '@/utils/currency';
;
export function useCurrency() {;
  const { _currentLanguage } = useLanguage();
;
  const formatPrice = (_amountUSD: number) => {;
    return formatPriceByLocale(amountUSD, currentLanguage);
  };
;
  return { formatPrice };
};
