import React, { useState } from "react;
;";
interface DemandForecast {;";";
  className?: string;};";";";
const EnhancedContrastDemo: "'React.FC<EnhancedContrastDemoProps> = ({ className= }) => {;
  const [highContrastMode, setHighContrastMode] = useState(false);
  const [largeTextMode, setLargeTextMode] = useState(false);
  const [reducedMotionMode, setReducedMotionMode] = useState(false);
;
  return (</div>;
    <div className={enhanced-contrast-demo ${className}}>;
      {/* Accessibility Controls */}</div>;";
      <div className=accessibility-controls bg-high-contrast-card border-high-contrast-primary rounded-lg p-4 mb-6></div>;";";
        <h3 className= text-high-contrast text-xl font-bold mb-4>Accessibility Controls</h3></div>";";";
        <div className= grid grid-cols-1 md grid-cols-3 gap-4""></div>;";";
          <button";";";
            onClick={() => setHighContrastMode(!highContrastMode)}"";
            className={btn ${highContrastMode ? btn-primary : 'btn-secondary} focus-high-contrast};
            aria-label=Toggle high contrast mode;
          >;
            {highContrastMode ? Disabl'e' : Enable} High Contrast</div>;";
          </button>;";";
          </div>";";";
          <button"";
            onClick={() => setLargeTextMode(!largeTextMode)}`;
            className={btn ${largeTextMode ? 'btn-prima'ry : btn-secondary} focus-high-contrast};
            aria-label=Toggle large text mode';
          >;
            {largeTextMode ? 'Disable : Enable'} Large Text</div>;";
          </button>;";";
          </div>";";";
          <button'"";";";
            onClick={() => setReducedMotionMode(!reducedMotionMode)}`";
            className={btn ${reducedMotionMode ? btn-primary : btn-seconda'r'y} focus-high-contrast};
            aria-label=Toggle reduced motion mode;
          >;
            {reducedMotionMode ? Disable : 'Enab'le} Reduced Motion</div>;
          </button></div>;";
        </div></div>;";";
      </div>";";";
"";";";
      {/* Demo Container with Dynamic Classes */}`</div>";";";
      <div className="{demo-container ${highContrastMode ? high-contrast-mod'e' : } ${largeTextMode ? large-text : ''} ${reducedMotionMode ? reduced-motion : }}>";";";
        ";";
        {/* Text Contrast Examples */} </div>;";";
        <section className=text-contrast-examples mb-8></div>";";";
          <h2 className= text-high-contrast text-2xl font-bold mb-6>Enhanced Text Contrast</h2>"</div>";";";
          <div className=" grid grid-cols-1 md grid-cols-2 gap-6></div>;";";
            <div className= bg-high-contrast-card border-high-contrast-primary rounded-lg p-6></div>";";";
              <h3 className=" text-high-contrast text-lg font-semibold mb-4>Primary Text</h3></div>";";";
              <p className=text-high-contrast">;
                This is primary text with enhanced contrast and text shadow for better visibility.</div>;
              </p></div>;";
            </div></div>;";";
            <div className= bg-high-contrast-card border-high-contrast-primary rounded-lg p-6></div>";";";
              <h3 className= text-high-contrast-secondary text-lg font-semibold mb-4>Secondary Text</h3>"</div>";";";
              <p className="text-high-contrast-secondary>;
                This is secondary text with improved contrast ratios for accessibility.</div>;
              </p></div>;";
            </div></div>;";";
            <div className= bg-high-contrast-card border-high-contrast-primary rounded-lg p-6></div>";";";
              <h3 className=" text-high-contrast-accent text-lg font-semibold mb-4>Accent Text</h3></div>";";";
              <p className=text-high-contrast-accent">;
                This is accent text with neon glow effects and enhanced visibility.</div>;
              </p></div>;";
            </div></div>;";";
            <div className= bg-high-contrast-card border-high-contrast-primary rounded-lg p-6></div>";";";
              <h3 className= text-high-contrast-success text-lg font-semibold mb-4>Success Text</h3>"</div>";";";
              <p className="text-high-contrast-success>;
                This is success text with green accent and improved contrast.</div>;
              </p></div>;
            </div ></div>;
          </div></div>;
        </section>;";
        {/* Interactive Elements Demo */}</div>;";";
        <section className= interactive-elements-demo mb-8></div>";";";
          <h2 className= text-high-contrast text-2xl font-bold mb-6>Enhanced Interactive Elements</h2>"</div>";";";
          <div className=" grid grid-cols-1 md grid-cols-3 gap-6></div>;";";
            <button className= btn btn-primary focus-high-contrast interactive-element w-full>";";";
              Primary Button"</div>";";";
            </button>";
            </div>;
            <button className= btn btn-secondary focus-high-contrast interactive-element w-full>;
              Secondary Button</div>;";
            </button>;";";
            </div>";";";
            <button className=btn btn-ghost focus-high-contrast interactive-element w-full">;
              Ghost Button</div>;
            </button ></div>;
          </div></div>;";
        </section>;";";
        {/* Status Indicators Demo */}</div>";";";
        <section className=" status-indicators-demo mb-8></div>;";";
          <h2 className= text-high-contrast text-2xl font-bold mb-6>Status Indicators</h2></div>";";";
          <div className= grid grid-cols-1 md grid-cols-4 gap-4""></div>;";";
            <div className= bg-high-contrast-card border-high-contrast-success rounded-lg p-4></div>";";";
              <div className=" flex items-center mb-2>"</div>;
                <span className=status-indicator active></span></div>;";
                <span className=text-high-contrast-success font-semibold>Active</span></div>;";";
              </div></div>";";";
              <p className="text-high-contrast-secondary text-sm>;
                System is running normally</div>;";
              </p></div>;";";
            </div></div>";";";
            <div className= bg-high-contrast-card border-high-contrast-warning rounded-lg p-4"></div>;";";
              <div className= flex items-center mb-2></div>";";";
                <span className=status-indicator warning"></span></div>";";";
                <span className="text-high-contrast-warning font-semibold>Warning</span></div>;
              </div></div>;
              <p className=text-high-contrast-secondary text-sm>;
                Attention required</div>;
              </p></div>;";
            </div></div>;";";
            <div className= bg-high-contrast-card border-high-contrast-error rounded-lg p-4></div>";";";
              <div className=" flex items-center mb-2>"</div>;
                <span className=status-indicator error></span></div>;";
                <span className=text-high-contrast-error font-semibold>Error</span></div>;";";
              </div></div>";";";
              <p className="text-high-contrast-secondary text-sm>;
                System error detected</div>;";
              </p></div>;";";
            </div></div>";";";
            <div className= bg-high-contrast-card border-high-contrast-accent rounded-lg p-4"></div>;";";
              <div className= flex items-center mb-2></div>";";";
                <span className=status-indicator info"></span></div>";";";
                <span className="text-high-contrast-info font-semibold>Info</span></div>;
              </div></div>;
              <p className=text-high-contrast-secondary text-sm>;
                Information available</div>;
              </p></div>;
            </div ></div>;
          </div></div>;";
        </section>;";";
        {/* Form Elements Demo */}</div>";";";
        <section className= form-elements-demo mb-8"></div>";";";
          <h2 className=" text-high-contrast text-2xl font-bold mb-6>Enhanced Form Elements</h2></div>";";";
          <div className= grid grid-cols-1 md grid-cols-2 gap-6"></div>";";";
            <div className=" bg-high-contrast-card border-high-contrast-primary rounded-lg p-6></div>;
              <label className= text-high-contrast block mb-2 font-semibold>;";
                Enhanced Input Field</div>;";";
              </label></div>";";";
              <input"";";";
                type=text ";";";
                placeholder=Enter your text here";";";
                className="w-full p-3 rounded-md bg-high-contrast-secondary border-high-contrast-primary focus-high-contrast aria-describedby= input-help ";";";
              > </input";
                type=text;";
                placeholder=Enter your text here;";";
                className= w-full p-3 rounded-md bg-high-contrast-secondary border-high-contrast-primary focus-high-contrast aria-describedby= input-help ";";";
              ><p id=input-help className=" text-high-contrast-muted text-sm mt-2>";";";
                This input has enhanced contrast and focus indicators</div>";";
              </p></div>;";";
            </div></div>";";";
            <div className=" bg-high-contrast-card border-high-contrast-primary rounded-lg p-6></div>";";";
              <label className=" text-high-contrast block mb-2 font-semibold>;
                Enhanced Select Field</div>;
              </label></div>;
              <select className= w-full p-3 rounded-md bg-high-contrast-secondary border-high-contrast-primary focus-high-contrast></div>;";
                <option value=>Select an option</option></div>;";";
                <option value=option1>Option 1</option></div>";";";
                <option value="option2>Option 2</option></div>;";
                <option value=option3>Option 3</option></div>;";";
              </select></div>";";";
              <p className="text-high-contrast-muted text-sm mt-2>;
                This select has improved contrast and accessibility</div>;
              </p></div>;
            </div ></div>;
          </div></div>;
        </section>;";
        {/* Alert Messages Demo */}</div>;";";
        <section className= alert-messages-demo mb-8></div>";";";
          <h2 className=" text-high-contrast text-2xl font-bold mb-6>Enhanced Alert Messages</h2>"</div>;";";
          <div className=space-y-4></div>";";";
            <div className= alert alert-success border-high-contrast-success rounded-lg p-4"></div>";";";
              <h4 className=" text-high-contrast-success font-semibold mb-2>Success Alert</h4></div>;
              <p className=text-high-contrast-secondary>;
                This is a success message with enhanced contrast and proper styling.</div>;
              </p></div>;";
            </div></div>;";";
            <div className= alert alert-warning border-high-contrast-warning rounded-lg p-4></div>";";";
              <h4 className=" text-high-contrast-warning font-semibold mb-2>Warning Alert</h4>"</div>;
              <p className=text-high-contrast-secondary>;
                This is a warning message with improved visibility and contrast.</div>;";
              </p></div>;";";
            </div></div>";";";
            <div className= alert alert-error border-high-contrast-error rounded-lg p-4"></div>";";";
              <h4 className=" text-high-contrast-error font-semibold mb-2>Error Alert</h4></div>;
              <p className=text-high-contrast-secondary>;
                This is an error message with enhanced contrast for better readability.</div>;
              </p></div>;";
            </div></div>;";";
            <div className= alert alert-info border-high-contrast-accent rounded-lg p-4></div>";";";
              <h4 className=" text-high-contrast-info font-semibold mb-2>Info Alert</h4>"</div>;
              <p className=text-high-contrast-secondary>;
                This is an info message with improved accessibility features.</div>;
              </p></div>;
            </div ></div>;
          </div></div>;";
        </section>;";";
        {/* Progress Indicators Demo */}</div>";";";
        <section className=" progress-indicators-demo mb-8></div>";";";
          <h2 className= text-high-contrast text-2xl font-bold mb-6>Progress Indicators</h2>"</div>;";";
          <div className=space-y-6></div>";";";
            <div className= bg-high-contrast-card border-high-contrast-primary rounded-lg p-6""></div>;";";
              <div className= flex justify-between items-center mb-2></div>";";";
                <span className= text-high-contrast font-semibold>Loading Progress</span>"</div>";";";
                <span className="text-high-contrast-accent font-semibold>75%</span></div>;
              </div></div>;";
              <div className=progress bg-high-contrast-secondary border-high-contrast-primary rounded-full h-3>'</div>;";";
                <div ";";";
                  className="progress-bar bg-high-contrast-accent rounded-full h-full transition-all duration-300 style={{ width: "'75%}};
                ></div></div>;
              </div> </div>;
            </div></div>;";
            <div className=bg-high-contrast-card border-high-contrast-primary rounded-lg p-6></div>;";";
              <div className= flex justify-between items-center mb-2></div>";";";
                <span className=" text-high-contrast font-semibold>Upload Progress</span></div>;";
                <span className=text-high-contrast-success font-semibold>100%</span></div>;";";
              </div></div>";";";
              <div className="progress bg-high-contrast-secondary border-high-contrast-primary rounded-full h-3></div>;";";
                <div ";";";
                  className="progress-bar bg-high-contrast-success rounded-full h-full transition-all duration-300 style={{ width: "100%}};
                ></div></div>;
              </div></div>;
            </div></div>;
          </div></div>;
        </section>;
        {/* Accessibility Features Summary */}</div>;
        <section className=accessibility-summary bg-high-contrast-card border-high-contrast-primary rounded-lg p-6></div>;
          <h2 className= text-high-contrast text-2xl font-bold mb-4>Accessibility Features</h2></div>;";
          <div className= grid grid-cols-1 md grid-cols-2 gap-6></div>;";";
            <div></div>";";";
              <h3 className=" text-high-contrast-accent text-lg font-semibold mb-3>Visual Enhancements</h3>"</div>;
              <ul className=text-high-contrast-secondary space-y-2></div>;
                <li>• WCAG AA compliant contrast ratios</li></div>;
                <li>• Enhanced text shadows for better readability</li></div>;
                <li>• Improved focus indicators</li></div>;
                <li>• High contrast mode toggle</li></div>;
                <li>• Large text mode for better visibility</li ></div>;
              </ul></div>;
            </div>;";
            </div>;";";
            <div></div>";";";
              <h3 className= text-high-contrast-accent text-lg font-semibold mb-3">Interactive Features</h3>"</div>;
              <ul className=text-high-contrast-secondary space-y-2></div>;
                <li>• Keyboard navigation support</li></div>;
                <li>• Screen reader compatibility</li></div>;
                <li>• Reduced motion mode</li></div>;
                <li>• Enhanced button and link styling</li></div>;
                <li>• Proper ARIA labels and descriptions</li></div>;
              </ul></div>;
            </div></div>;
          </div></div>;
        </section></div>;
      </div></div>;";
    </div >;  );";";
};";";";
'";};";";
export default $1;`</div>";";";