import React, { useState } from 'react'
  gradient?: 'blue' | 'purple' | 'green' | 'pink' | 'custom'
  className = ''
  gradient = 'blue'
    blue: 'from-neon-blue/20 to-neon-purple/20'
    purple: 'from-neon-purple/20 to-neon-pink/20'
    green: 'from-neon-green/20 to-neon-blue/20'
    pink: 'from-neon-pink/20 to-neon-purple/20'
    custom: 'from-neon-blue/20 via-neon-purple/20 to-neon-pink/20'
    blue: 'shadow-neon-blue/20 hover:shadow-neon-blue/40'
    purple: 'shadow-neon-purple/20 hover:shadow-neon-purple/40'
    green: 'shadow-neon-green/20 hover:shadow-neon-green/40'
    pink: 'shadow-neon-pink/20 hover:shadow-neon-pink/40'
    custom: 'shadow-neon-blue/20 hover:shadow-neon-blue/40'
    ${border ? 'border border-white/10' : ''
    ${glow ? glowClasses[gradient] : ''
    ${hover ? 'transition-all duration-500 transform hover:scale-105' : ''
    ${animated ? 'animate-pulse' : ''
    ${onClick ? 'cursor-pointer' : ''