import React, { useState, useEffect } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/router'
      if (typeof window !== 'undefined'
    if (typeof window !== 'undefined'
      window.addEventListener('scroll'
      return () => window.removeEventListener('scroll'
    { name: 'Home', href: '/', current: router.pathname === '/'
    { name: 'Services', href: '/services', current: router.pathname.startsWith('/services'
    { name: 'Talent', href: '/talent', current: router.pathname.startsWith('/talent'
    { name: 'Products', href: '/products', current: router.pathname.startsWith('/products'
    { name: 'Blog', href: '/blog', current: router.pathname.startsWith('/blog'
    { name: 'About', href: '/about', current: router.pathname === '/about'
          ? 'bg-white/90 backdrop-blur-md shadow-lg border-b border-gray-200/50'
          : 'bg-transparent'
                  isScrolled ? 'text-gray-900' : 'text-white'
                        ? 'text-blue-600 bg-blue-50'
                        ? 'text-gray-700 hover:text-blue-600 hover:bg-gray-50'
                        : 'text-white/90 hover:text-white hover:bg-white/10'
                    ? 'text-gray-700 hover:text-blue-600'
                    : 'text-white/90 hover:text-white'
                    ? 'text-gray-700 hover:text-blue-600'
                    : 'text-white/90 hover:text-white'
                      ? 'text-blue-600 bg-blue-50'
                      : 'text-gray-700 hover:text-blue-600 hover:bg-gray-50'