import { useState, useEffect, useCallback } from 'react'
import { useNotifications } from './NotificationSystem'
  const [feedbackComment, setFeedbackComment] = useState(''
        type: 'info'
        title: 'Discover More'
        message: 'Explore our AI-powered services and find the perfect solution for your needs.'
          label: 'Explore Services'
            onUserAction?.('explore_services'
            window.location.href = '/services'
        type: 'success'
        title: 'Welcome to Zion!'
        message: 'You\'ve been exploring for a minute. Ready to get started?'
          label: 'Get Started'
            onUserAction?.('get_started'
            window.location.href = '/auth'
        type: 'success'
        title: 'Thank You!'
        message: 'Your feedback helps us improve. We appreciate your input!'
      onUserAction?.('feedback_submitted'
      setFeedbackComment(''
      type: 'info'
      title: 'Quick Actions'
      message: 'Need help? Try our quick actions below.'
                      star 
        <button onClick={() => handleInteraction('service_click'
        <button onClick={() => handleInteraction('talent_click'
        <button onClick={() => handleInteraction('product_click'
        <button onClick={() => handleInteraction('auth_click'