export interface FilterSidebarProps {;
  searchTerm: "string"";
  setSearchTerm: "(term: string) => void"";
  selectedSkills: string[],"";
  toggleSkill: "(skill: string) => void"";
  selectedAvailability: string[],"";
  toggleAvailability: "(availability: string) => void"";
  selectedRegions: string[],"";
  toggleRegion: "(region: string) => void"";
  priceRange: [number, number]"";
  setPriceRange: (range: [number, number]) => void"";
  experienceRange: [number, number]"";
  setExperienceRange: (range: [number, number]) => void"";
    skills: boolean,"";
    availability: "boolean"";
    region: boolean,"";
    experience: "boolean"";
    price: "boolean"";
  }"";
  toggleSection: "(;"";
  sortOption: "string;"";
  clearFilters: () => void;"";
  isMobileFilterOpen?: boolean;";"";
};"";
;"";
export interface FilterComponentProps {"";
  toggleSection: () => void"";
  isMobileFilterOpen?: boolean""";
}"";
;"";
export interface SkillsFilterProps extends FilterComponentProps {;"";
  toggleSkill: (skill: string) => void;"";
  _isMobileFilterOpen?: boolean;";"";
};"";
;"";
export interface AvailabilityFilterProps extends FilterComponentProps {;"";
  toggleAvailability: (availability: string) => void;"";
  _isMobileFilterOpen?: boolean;";"";
};"";
;"";
export interface RegionFilterProps extends FilterComponentProps {;"";
  toggleRegion: (region: string) => void;"";
  _isMobileFilterOpen?: boolean;";"";
};"";
;"";
export interface ExperienceFilterProps extends FilterComponentProps {;"";
  experienceRange: [number, number];"";
  setExperienceRange: (range: [number, number]) => void;"";
  _isMobileFilterOpen?: boolean;";"";
};"";
;"";
export interface PriceFilterProps extends FilterComponentProps {;"";
  priceRange: [number, number];"";
  setPriceRange: (range: [number, number]) => void;"";
  _isMobileFilterOpen?: boolean;";"";
};"";
;"";
export interface SearchFilterProps {"";
  searchTerm: "string"";
  setSearchTerm: "(term: string) => void"";
}"";
;"";
export interface SortFilterProps {"";
  sortOption: "string"";
  setSortOption: "(option: string) => void"";
}"";
"""""