export interface ProfileSkill {;
  name: string,;
  level: number // 1-5"";
  endorsements?: number""";
}"";
;"";
export interface ProfileProject {"";
  id: "string"";
  title: string,"";
  description: string""";
  imageUrl?: string"";
  tags?: string[]"";
  url?: string"";
  date: "string"";
}"";
;"";
export interface ProfileExperience {"";
  id: "string"";
  role: string,"";
  company: "string"";
  endDate?: string"";
  current?: boolean""";
}"";
;"";
export interface Availability {;"";
  availableHours?: { day: "string; hours: string "}[];"";
};"";
;"";
export interface ProfileData {"";
  id: "string"";
  name: string,"";
  bio: string"";
  location?: string""";
  rating?: number"";
  reviewCount?: number"";
  aiScore?: number"";
  skills: ProfileSkill[],"";
  projects: "ProfileProject[]"";
  availability: Availability"";
  hourlyRate?: number""";
  contactEmail?: string"";
}"";
"""""