}> = ({;
  sortBy,;
  setSortBy,;
  filterCategory,;
  setFilterCategory,;
  categories,;
  priceRange,;
  setPriceRange,;
  minAiScore,;
  setMinAiScore,;
  minRating,;
  setMinRating,;
  filterAvailability,;
  setFilterAvailability,;
  availabilityOptions,;
  filterLocation,;
  setFilterLocation,;