<Link href={`/project/${project.id}`}>View Details</Link>;
                  </Button>;
                </CardFooter>;
              </Card>;
            ))};
          </div>;
        )};
      </main>;
    </>;
  );