import { useRouter } from 'next/router'
import { useState, useEffect } from 'react'
import { createClient } from '@supabase/supabase-js'
  const [verificationStatus, setVerificationStatus] = useState('verifying'
  const [error, setError] = useState(''
        setVerificationStatus('error'
        setVerificationStatus('success'
      setError('An unexpected error occurred'
      setVerificationStatus('error'
          {verificationStatus === 'verifying'
          {verificationStatus === 'success'
                onClick={() => router.push('/auth/login'
          {verificationStatus === 'error'
                onClick={() => router.push('/auth/login'