import React from 'react'
import { useRouter } from 'next/router'
import { findRouteByPath } from '@/utils/routeUtils'
import { SEO } from './SEO'
import { getAppConfig } from '@/utils/config'
'
/**'
 * Renders default SEO tags based on the current route's metadata.'