import React, { useState, useEffect, useRef } from 'react''
import { Search, X } from '@/components/ui/icons'
import { useRouter } from 'next/router'

import { Input } from '@/components/ui/input'
import { AutocompleteSuggestions } from '@/components/search/AutocompleteSuggestions'
import { fireEvent } from '@/lib/analytics'
import type { SearchSuggestion } from '@/types/search'
import { useDebounce } from '@/hooks/useDebounce'
import { useOnClickOutside } from '@/hooks/useOnClickOutside'