import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { Building2, Globe, Shield, Zap } from 'lucide-react';
const companies = [
    { name: 'TechCorp', logo: _jsx(Building2, { className: "w-8 h-8" }), industry: 'Technology' },
    { name: 'GlobalNet', logo: _jsx(Globe, { className: "w-8 h-8" }), industry: 'Telecommunications' },
    { name: 'SecureTech', logo: _jsx(Shield, { className: "w-8 h-8" }), industry: 'Cybersecurity' },
    { name: 'InnovateLab', logo: _jsx(Zap, { className: "w-8 h-8" }), industry: 'Research & Development' },
];
export const TrustedBySection = () => {
    return (_jsx("section", { className: "py-16 bg-zion-blue-dark/50", children: _jsxs("div", { className: "container mx-auto px-4", children: [_jsxs(motion.div, { initial: { opacity: 0, y: 30 }, whileInView: { opacity: 1, y: 0 }, transition: { duration: 0.8 }, className: "text-center mb-12", children: [_jsx("h2", { className: "text-3xl md:text-4xl font-bold text-white mb-4", children: "Trusted by Leading Companies" }), _jsx("p", { className: "text-zion-slate-light text-lg max-w-2xl mx-auto", children: "Join hundreds of organizations that rely on our expertise to drive innovation and growth" })] }), _jsx("div", { className: "grid grid-cols-2 md:grid-cols-4 gap-8", children: companies.map((company, index) => (_jsxs(motion.div, { initial: { opacity: 0, scale: 0.8 }, whileInView: { opacity: 1, scale: 1 }, transition: { duration: 0.5, delay: index * 0.1 }, className: "text-center group", children: [_jsx("div", { className: "flex items-center justify-center mb-4", children: _jsx("div", { className: "p-4 bg-zion-cyan/20 rounded-xl text-zion-cyan group-hover:bg-zion-cyan group-hover:text-white transition-all duration-300", children: company.logo }) }), _jsx("h3", { className: "text-lg font-semibold text-white mb-2", children: company.name }), _jsx("p", { className: "text-sm text-zion-slate-light", children: company.industry })] }, company.name))) }), _jsx(motion.div, { initial: { opacity: 0, y: 30 }, whileInView: { opacity: 1, y: 0 }, transition: { duration: 0.8, delay: 0.5 }, className: "text-center mt-12", children: _jsxs("div", { className: "inline-flex items-center space-x-2 text-zion-slate-light", children: [_jsx("span", { children: "Join them today" }), _jsx("span", { className: "text-zion-cyan", children: "\u2192" })] }) })] }) }));
};
