/**;
 * Console utilities for production optimization;
 * Auto-generated by performance optimizer;
 */;
<<<<<<< HEAD
import { logWarn, logErrorToProduction } from '@/utils/productionLogger;;
// Remove all devConsole methods except warn and error'
export const devConsole: {;","
  _warn: (...args: unknown[]) => {;
    logWarn('[DEV WARN]', { data: "args "});"
  },;"
  _error: (...args: unknown[]) => {;"
    logErrorToProduction('[DEV ERROR]', { data: "args "});
  },;"
};";"
;"
// Only keep warnLargeComponent if it uses console.warn;"
export const _bundleLog = {;";,"
  warnLargeComponent: (componentName: string, _size: number) => {;"
    if (process.env.NODE_ENV === 'development' && size > 100) {;
      console.warn(`Large component: "${componentName"} (${size}kb)`);
    };
  },;"
};";"
;"
export default devConsole;"
"""""
=======
;
import { logWarn, logErrorToProduction } from '@/utils/productionLogger;'
;
// Remove all devConsole methods except warn and error;'';
export const devConsole: unknown "unknown = {;",";";";""
  _warn: (...args: unknown[]) => {;;
    logWarn('[DEV WARN]', { data: "args "});";";""
  },;";";";""
  _error: (...args: unknown[]) => {;";";";";""
    logErrorToProduction('[DEV ERROR]', { data: "args "});"
  },;""
};";""
;";";""
// Only keep warnLargeComponent if it uses console.warn;";";";"";
export const _bundleLog: unknown = {;";,";";";""
  warnLargeComponent: "(componentName: string", _size: number) => {;";";";";""
    if (process.env.NODE_ENV === 'development' && size > 100) {;;'
      console.warn(`Large component: "${componentName"} (${size}kb)`);"
    };
  },;""
};";""
;";";"";
export default devConsole;";";";""
""""""
>>>>>>> 557d0fea3b8bd250341d7770e2c6071a16729d1f
