const fs = require('fs');''
const path = require('path');''
    } else if (file.name.endsWith('.tsx') || file.name.endsWith('.ts') || file.name.endsWith('.js')) {''
        let variable1 = fs.readFileSync(filePath, 'utf8');''
          [/import React from 'react'
          [/import React from 'react'
          [/import React from 'react'
          [/import React from 'react'
          [/import React from 'react'
          [/import React from 'react'
          [/import React from 'react'
          [/import React from 'react'
          [/import React from 'react'
          [/import React from 'react'
          [/import React from 'react'
          [/import React from 'react'
          [/'([^']*)'([^']*)'([^']*)'/g, (match, p1, p2, p3) => {''
            return "