/** Tiny honest closer for leftover Next.js / ghost SKU routes. */
export function titleFromSlug(slug) {
  const last = String(slug).replace(/\/index\.html$/, '').split('/').filter(Boolean).pop() || 'Page';
  return last
    .replace(/[-_]+/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
    .replace(/\bAi\b/g, 'AI')
    .replace(/\bIt\b/g, 'IT')
    .replace(/\bMsp\b/g, 'MSP')
    .replace(/\bSoc\b/g, 'SOC')
    .replace(/\bN8n\b/g, 'n8n');
}

export function honestCloser({ title, canonical = '/services/' }) {
  const safeTitle = String(title).replace(/[<>]/g, '');
  const href = canonical.startsWith('/') ? canonical : `/${canonical}`;
  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><title>${safeTitle} · Zion Tech Group</title>
<link rel="canonical" href="https://ziontechgroup.com${href}">
<meta name="description" content="Not a packaged SKU. Zion scopes work after the $99 AI/IT Discovery.">
<meta http-equiv="refresh" content="0; url=${href}">
<style>body{font-family:system-ui;background:#0b1220;color:#e6f0ff;max-width:720px;margin:0 auto;padding:48px 24px;line-height:1.65}a{color:#a78bfa}</style></head>
<body>
<h1>${safeTitle}</h1>
<p>No packaged SKU, no free consultation, and no leftover service catalog. Work is scoped after the $99 Discovery.</p>
<p><a href="/services/">Services</a> · <a href="/book/">Book $99</a> · <a href="/plans/">Prices</a></p>
</body></html>
`;
}

/** Ghost URLs Google still ranks (SerpAPI 2026-09-03) that currently 404 on Pages. */
export const SERP_CLOSER_PATHS = [
  'services/postgresql/index.html',
  'services/managed-it-services-small-business-2026-6559/index.html',
  'services/ai-observability-2026-6565/index.html',
  'services/cybersecurity-platform-msp-2026-6558/index.html',
  'services/cloud-cost-ai-optimizer-2026-6534/index.html',
  'services/prometheus/index.html',
  'services/ai-observability/index.html',
  'services/ai-sentiment-monitor/index.html',
  'services/ai-smart-global-campaign/index.html',
  'services/cloud-migration-services-2026-6572/index.html',
  'services/w174-database-admin-managed/index.html',
  'services/looking-glass-holographic-displays/index.html',
  'services/ai-recruitment-resume-screener/index.html',
  'services/ai-legal-discovery-platform/index.html',
  'services/optomec-aerosol-jet-3d-printing/index.html',
  'services/locus-autonomous-mobile-robots/index.html',
  'services/ai-chatbot-builder/index.html',
  'services/it-backup-disaster-recovery/index.html',
  'services/it-asset-management/index.html',
  'blog/cloud-cost-ai-optimizer-checklist-for-it-leaders/index.html',
  'services/it-it-asset-management/index.html',
  'services/it-asset-management-lifecycle/index.html',
  'services/it-network-monitoring/index.html',
  'services/ai-internal-app-builder/index.html',
  'services/ai-knowledge-base-faq-chatbot/index.html',
  'services/data-backup-recovery/index.html',
  'services/w177-it-backup-recovery/index.html',
  'services/ai-api-orchestration-layer/index.html',
  'services/it-hybrid-cloud-orchestrator/index.html',
  'services/langchain-langgraph-agent-orchestration/index.html',
  'services/saas-knowledge-base/index.html',
  'services/microsaas-knowledge-base-builder/index.html',
  'services/ai-email-personalization/index.html',
  'services/w174-monitoring-observability/index.html',
  'services/network-performance-monitoring-optimization/index.html',
  'services/w177-micro-saas-workos-auth/index.html',
  'services/w177-security-incident-response/index.html',
  'services/w177-cloud-cost-optimization/index.html',
  'services/w177-data-realtime-pipeline/index.html',
  'services/w177-automation-process-mining/index.html',
  'services/w174-tech-debt-assessment/index.html',
  'services/w174-reverse-etl/index.html',
  'services/w174-data-contracts/index.html',
  'services/w174-pentest-as-service/index.html',
  'services/w174-data-mesh-platform/index.html',
  'services/cloud-hybrid-orchestration/index.html',
  'services/cloud-hybrid-cloud-management/index.html',
  'services/intelligent-process-mining/index.html',
  'services/auto-rpa-platform/index.html',
  'services/w176-it-edge-delivery/index.html',
  'services/w176-micro-saas-analytics-starter/index.html',
  'services/w176-ai-voice-assistant-factory/index.html',
  'services/penetration-testing/index.html',
  'blog/devsecops-pipeline-2026/index.html',
  'services/data-mesh-platform/index.html',
  'services/data-data-lake-platform/index.html',
  'services/w174-cloud-events-platform/index.html',
  'services/data-warehouse-modernization/index.html',
  'services/data-lake-platform/index.html',
  'services/sec-pentest-service/index.html',
  'services/financial-data-warehouse/index.html',
  'services/data-lakehouse/index.html',
  'blog/5-proven-ai-automation-strategies-for-enterprise-workflow-optimization/index.html',
  'services/ai-quantum-optimizer/index.html',
  'tools/port-scanner/index.html',
  'tools/support-automation-roi-calculator/index.html',
  'blog/ai-observability-security-and-governance/index.html',
  'blog/ai-msp-security-compliance-implementation-playbook/index.html',
  'solutions/index.html',
  'solutions/ai-customer-experience-suite-for-enterprises/index.html',
  'solutions/ai-data-pipeline-modernization/index.html',
  'solutions/ai-iot-operations-for-enterprises/index.html',
  'solutions/managed-soc-for-msps/index.html',
  'community/index.html',
  'services/saas-invoice-generator/index.html',
  'services/ai-bookkeeping-automation/index.html',
  'services/microsaas-feature-voting/index.html',
  'services/identity-access-management/index.html',
  'services/ai-document-processing/index.html',
  'blog/cybersecurity-platform-msp-2026/index.html',
  'blog/ai-agent-frameworks-for-business-automation/index.html',
  'blog/ai-for-cybersecurity-operations-and-threat-hunting/index.html',
  'tools/box-shadow-generator/index.html',
  'tools/image-color-extractor/index.html',
  'tools/cron-expression-explainer/index.html',
  'services/saas-api-rate-limiter/index.html',
  'services/identity-governance-platform/index.html',
  'services/keycloak/index.html',
  'services/micro-saas-url-shortener-analytics/index.html',
  'services/micro-saas-knowledge-base-help-center/index.html',
  'services/security-zero-trust-network/index.html',
  'services/it-zero-trust-access/index.html',
  'services/zscaler-zero-trust-exchange/index.html',
  'blog/ai-finops-and-cloud-cost-optimization-with-machine-learning/index.html',
  'services/loki/index.html',
  'services/grafana-observability/index.html',
  'services/real-time-analytics/index.html',
  'services/monte-carlo-observability/index.html',
  'services/ai-financial-forecasting-copilot/index.html',
  'services/infrastructure-monitoring/index.html',
  'services/backstage-developer-portal/index.html',
  'services/pulumi-infrastructure-as-code/index.html',
  'services/pagerduty-incident-management/index.html',
  'services/micro-saas-subscription-analytics/index.html',
  'services/saas-subscription-analytics/index.html',
  'services/microsaas-subscription-billing/index.html',
  'services/support-chatbot/index.html',
  'tools/ai-service-router/index.html',
  'services/ai-autonomous-incident-response/index.html',
  'services/security-soc-ai-copilot/index.html',
  'services/terraform/index.html',
  'services/trivy/index.html',
  'services/betterstack-uptime-monitoring/index.html',
  'services/w174-uptimecanary/index.html',
  'services/w174-DevOps-accelerator/index.html',
  'services/cicd-pipeline-engineering/index.html',
  'services/w174-incident-response/index.html',
  'services/w174-siem-managed/index.html',
  'services/ai-cybersecurity-threat-hunting/index.html',
  'services/github-copilot-ai-code-generation/index.html',
  'services/infrastructure-as-code-scanner/index.html',
  'services/w174-network-automation/index.html',
  'services/it-data-center-modernization/index.html',
  'services/kubernetes-management/index.html',
  'services/linkerd/index.html',
  'services/github-copilot-code-review/index.html',
  'services/ai-cyber-threat-hunting/index.html',
  'services/security-threat-intel-platform/index.html',
  'services/ai-code-security-scanner/index.html',
  'services/ai-smart-contract-auditor/index.html',
  'services/w174-ml-ops-platform/index.html',
  'services/cloud-serverless-application-platform/index.html',
  'services/mostly-ai-synthetic-data-platform/index.html',
  'services/weights-and-biases-mlops/index.html',
  'services/ai-smart-contract-lifecycle/index.html',
  'services/snyk-ai-code-security/index.html',
  'services/it-data-center-relocation/index.html',
  'services/threat-intelligence/index.html',
  'services/fermyon-spin-wasm-runtime/index.html',
  'services/ai-synthetic-data-platform/index.html',
];
