import Head from 'next/head';

export default function Page() {
  return (
    <div className="min-h-screen bg-slate-950 text-white">
      <Head>
        <title>Innovation Insight — 2025-08-13 22-20</title>
        <meta name="description" content="An inventive insight derived from autonomous research." />
        <meta property="og:title" content="Innovation Insight — 2025-08-13 22-20" />
        <meta property="og:description" content="An inventive insight derived from autonomous research." />
        <meta name="twitter:card" content="summary_large_image" />
      </Head>
      <main className="container mx-auto px-6 py-12 prose prose-invert">
        <h1 className="text-3xl font-extrabold">Innovation Insight — 2025-08-13 22-20</h1>
        <div className="mt-4">
          <ul className="list-disc pl-6">
            <li>Opportunity: Transform recurring signals into structured guides</li>
            <li>Idea: Build a feature row summarizing value, capability, and link to details</li>
            <li>
              Source:{' '}
              <a className="text-cyan-300 underline" href="https://ziontechgroup.com/explore" target="_blank" rel="noopener">
                https://ziontechgroup.com/explore
              </a>
            </li>
          </ul>
        </div>
        <p className="mt-6 text-white/60 text-sm">Auto-generated by Cloud Content Factory.</p>
      </main>
    </div>
  );
}

import Head from 'next/head';

export default function InsightPage() {
  return (
    <div className="min-h-screen bg-slate-950 text-white">
      <Head>
        <title>Checklist: Edge AI</title>
        <meta name="description" content="Patterns to increase accuracy." />
        <meta property="og:title" content="Checklist: Edge AI" />
        <meta property="og:description" content="Patterns to increase accuracy." />
        <meta name="twitter:card" content="summary_large_image" />
      </Head>
      <main className="container mx-auto px-6 py-12 prose prose-invert">
        <h1 className="text-3xl font-extrabold">Checklist: Edge AI</h1>
        <p className="text-white/70">Patterns to increase accuracy.</p>
        <ul className="mt-6 list-disc pl-6 space-y-2">
          <li>Scope: Checklist: Edge AI.</li>
          <li>Signals: AI Services.</li>
          <li>Architecture: ingestion → retrieval → reasoning → evaluation.</li>
          <li>Ops: observability, rollback, SLOs, security.</li>
        </ul>
        <p className="mt-6">More at <a className="text-cyan-300 underline" href="https://ziontechgroup.com" target="_blank" rel="noopener">ziontechgroup.com</a>.</p>
      </main>
    </div>
  );
}
