import { useState } from 'react''
import type { Resume } from '@/types/resume'
import { useFetchResume } from './useFetchResume'
import { useResumeActions } from './useResumeActions'
import { useWorkExperience } from './useWorkExperience'
import { useEducation } from './useEducation'
import { useSkills } from './useSkills'
import { useCertifications } from './useCertifications'
import  { useResumeList }  from './useResumeList'
export function useResume(): ;