<<<<<<< HEAD;

import * as AlertDialogPrimitive from '@radix-ui/react-alert-dialog;'';

import { buttonVariants } from '@/components/ui/button;'';
  React.ElementRef<typeof AlertDialogPrimitive.Overlay>,;''';
  <AlertDialogPrimitive.Overlay;''';
      'fixed inset-0 z-50 bg-black/80  data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0',;'';

  <AlertDialogPortal>;''';
      ref={ref};''';
        'fixed left-[50%] top-[50%] z-50 grid w-full max-w-lg translate-x-[-50%] translate-y-[-50%] gap-4 border bg-background p-6 shadow-lg duration-200 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[state=closed]:slide-out-to-left-1/2 data-[state=closed]:slide-out-to-top-[48%] data-[state=open]:slide-in-from-left-1/2 data-[state=open]:slide-in-from-top-[48%] sm:rounded-lg',;'';
  <AlertDialogPortal>'';
    <AlertDialogOverlay />'';
      ref={ref}'';
      className={cn('';
        'fixed left-[50%] top-[50%] z-50 grid w-full max-w-lg translate-x-[-50%] translate-y-[-50%] gap-4 border bg-background p-6 shadow-lg duration-200 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[state=closed]:slide-out-to-left-1/2 data-[state=closed]:slide-out-to-top-[48%] data-[state=open]:slide-in-from-left-1/2 data-[state=open]:slide-in-from-top-[48%] sm:rounded-lg','';
  className,;''';
  <div;''';
      'flex flex-col space-y-2 text-center sm:text-left',;'';
      className,;''';
  />;''';
AlertDialogHeader.displayName = 'AlertDialogHeader;'';
  className,;''';
  <div;''';
      'flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-2',;'';
      className,;''';
  />;''';
AlertDialogFooter.displayName = 'AlertDialogFooter;'';
  React.ElementRef<typeof AlertDialogPrimitive.Title>,;''';
  <AlertDialogPrimitive.Title;''';
    className={cn('text-lg font-semibold', className)};'';
  className,'';
  ...props'';
  <div'';
    className={cn('';
      'flex flex-col space-y-2 text-center sm:text-left','';
      className,'';
    )}'';
  />'';
)'';
AlertDialogHeader.displayName = 'AlertDialogHeader'';
  className,'';
  ...props'';
  <div'';
    className={cn('';
      'flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-2','';
      className,'';
    )}'';
  />'';
)'';
AlertDialogFooter.displayName = 'AlertDialogFooter'';
  React.ElementRef<typeof AlertDialogPrimitive.Title>,'';
  React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Title>'';
  <AlertDialogPrimitive.Title'';
    ref={ref}'';
    className={cn('text-lg font-semibold', className)}'';
  React.ElementRef<typeof AlertDialogPrimitive.Description>,;''';
  <AlertDialogPrimitive.Description;''';
    className={cn('text-sm text-muted-foreground', className)};'';
  React.ElementRef<typeof AlertDialogPrimitive.Description>,'';
  React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Description>'';
  <AlertDialogPrimitive.Description'';
    ref={ref}'';
    className={cn('text-sm text-muted-foreground', className)}'';
  React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Cancel>;''';
    ref={ref};''';
      buttonVariants({ variant: 'outline' }),;;'';
      'mt-2 sm:mt-0',;'';
  React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Cancel>'';
>(({ className, ...props }, ref) => ('';
    ref={ref}'';
    className={cn('';
      buttonVariants({ variant: 'outline' }),'';
      'mt-2 sm:mt-0','';
  AlertDialogDescription,;''';
};''';
''''''';
  AlertDialogDescription,'';
  AlertDialogAction,'';
}'';
'''''''