/**
 * Optimized icon imports - reduces bundle size by using tree-shaking
 * Auto-generated by performance optimizer
 */
export {
  // Navigation icons
  Search,
  Filter,
  X,
  Menu,
  Home,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ArrowLeft,
  ArrowRight,
  
  // User interface icons
  User,
  Users,
  Settings,
  LogIn,
  LogOut,
  Plus,
  Minus,
  Edit,
  Trash2,
  Eye,
  EyeOff,
  
  // Status icons
  Check,
  X as Close,
  AlertCircle,
  AlertTriangle,
  Info,
  Loader2,
  
  // Business icons
  ShoppingCart,
  Package,
  CreditCard,
  TrendingUp,
  BarChart,
  
  // Tech icons
  Server,
  Database,
  Code,
  Wifi,
  
  // File icons
  Download,
  Upload,
  File,
  Folder,
  
} from 'lucide-react';

// Icon groups for easy consumption
export const NavigationIcons = {
  Search, Filter, X, Menu, Home,
  ChevronDown, ChevronUp, ChevronLeft, ChevronRight,
  ArrowLeft, ArrowRight,
};

export const UserIcons = {
  User, Users, Settings, LogIn, LogOut,
};

export const StatusIcons = {
  Check, AlertCircle, AlertTriangle, Info, Loader2,
};

export const BusinessIcons = {
  ShoppingCart, Package, CreditCard, TrendingUp, BarChart,
};
